[package]
name = "rustring_builder"
version = "0.2.0"
edition = "2021"
authors = ["Tal Riginiano"]
license = "MIT"
description = "A Rust string builder"
keywords = ["stringbuilder", "string", "builder","sql"]
[dependencies]
